/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Date;
import ConexionBBDD.ConexionBBDD;
import java.sql.Connection;

/**
 *
 * @author DAM2Alu14
 */
public class JDialogAltaUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogAltaUsuario.class.getName());

    // TERMINAR AL INSERTAR USUARIO  ES OBLIGATTORIO EL ID_PLAN
    
    /**
     * Creates new form JDialogAltaCliente
     */
    Connection conexion;
    JFrameUsuarios padre;
    
    public JDialogAltaUsuario(java.awt.Frame parent, boolean modal, Connection conexionPadre) {
        padre = (JFrameUsuarios) parent;
        initComponents();

        this.conexion = conexionPadre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPlanId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordNueva = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordConfirmar = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jComboRol = new javax.swing.JComboBox<>();
        jButtonAlta = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("ALTA USUARIOS");

        jPanel1.setLayout(new java.awt.GridLayout(5, 2, 10, 10));

        jLabel2.setText("Plan_ID");
        jPanel1.add(jLabel2);
        jPanel1.add(jTextFieldPlanId);

        jLabel3.setText("Usuario");
        jPanel1.add(jLabel3);
        jPanel1.add(jTextFieldUsuario);

        jLabel8.setText("Nueva Contraseña");
        jPanel1.add(jLabel8);
        jPanel1.add(jPasswordNueva);

        jLabel4.setText("Confirmar Contraseña");
        jPanel1.add(jLabel4);
        jPanel1.add(jPasswordConfirmar);

        jLabel6.setText("Rol");
        jPanel1.add(jLabel6);

        jComboRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrenador", "Administrador", "Profesor" }));
        jPanel1.add(jComboRol);

        jButtonAlta.setText("Alta");
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });

        jButtonCerrar.setText("Cancelar");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jButtonAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCerrar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlta)
                    .addComponent(jButtonCerrar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
        // Obtener los datos de los campos
        String planIdStr = jTextFieldPlanId.getText().trim();
        String usuario = jTextFieldUsuario.getText().trim();
        String pass1 = new String(jPasswordNueva.getPassword());
        String pass2 = new String(jPasswordConfirmar.getPassword());
        String rol = jComboRol.getSelectedItem().toString();

        // Validar solo los campos obligatorios
        if (usuario.isEmpty() || pass1.isEmpty() || pass2.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Usuario y contraseña son obligatorios.", "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Verificar que las contraseñas coincidan
        if (!pass1.equals(pass2)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Las contraseñas no coinciden.", "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Verificar que el nombre de usuario no exista ya
            PreparedStatement psCheck = conexion.prepareStatement(
                "SELECT COUNT(*) FROM usuario WHERE Usuario = ?"
            );
            psCheck.setString(1, usuario);
            java.sql.ResultSet rs = psCheck.executeQuery();
            
            if (rs.next() && rs.getInt(1) > 0) {
                // El usuario ya existe
                javax.swing.JOptionPane.showMessageDialog(this,
                        "El nombre de usuario ya existe. Por favor, elija otro.", "Error",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                rs.close();
                psCheck.close();
                return;
            }
            rs.close();
            psCheck.close();

            // Preparar la consulta INSERT
            PreparedStatement ps = conexion.prepareStatement(
                "INSERT INTO usuario (Plan_ID, Usuario, Contrasena, Rol) VALUES (?, ?, ?, ?)"
            );

            // Manejar Plan_ID como opcional
            if (!planIdStr.isEmpty()) {
                try {
                    // Si hay valor, convertir a entero
                    ps.setInt(1, Integer.parseInt(planIdStr));
                } catch (NumberFormatException ex) {
                    // Si no es un número válido, mostrar error
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Plan_ID debe ser un número válido.", "Error",
                            javax.swing.JOptionPane.ERROR_MESSAGE);
                    ps.close();
                    return;
                }
            } else {
                // Si está vacío, insertar NULL
                ps.setNull(1, java.sql.Types.INTEGER);
            }

            // Establecer los demás parámetros
            ps.setString(2, usuario);
            ps.setString(3, pass1);
            ps.setString(4, rol);

            // Ejecutar la inserción
            ps.executeUpdate();
            ps.close();

            // Mostrar mensaje de éxito
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario creado correctamente.");

            // Actualizar la tabla del padre
            padre.cargarUsuarios();

            // Cerrar el diálogo
            dispose();

        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error al insertar usuario", ex);

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al insertar en la base de datos: " + ex.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAltaActionPerformed
    
    
    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new JDialogAltaCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JComboBox<String> jComboRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordConfirmar;
    private javax.swing.JPasswordField jPasswordNueva;
    private javax.swing.JTextField jTextFieldPlanId;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
