/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Date;
import ConexionBBDD.ConexionBBDD;
import java.sql.Connection;

/**
 *
 * @author DAM2Alu14
 */
public class JDialogAltaSocio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogAltaSocio.class.getName());

    /**
     * Creates new form JDialogAltaCliente
     */
    Connection conexion;
    JFrameGestionSocios jframepadre;
    
    public JDialogAltaSocio(java.awt.Frame parent, boolean modal, Connection conexionPadre) {
        jframepadre =(JFrameGestionSocios)parent;
        initComponents();

        this.conexion = conexionPadre; // Usamos la misma conexión que el padre
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldApellido2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldApellidoDNI = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSpinnerFechaAlta = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jButtonAlta = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("ALTA CLIENTES");

        jPanel1.setLayout(new java.awt.GridLayout(8, 2, 10, 10));

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2);
        jPanel1.add(jTextFieldNombre);

        jLabel3.setText("Primer Apellido");
        jPanel1.add(jLabel3);
        jPanel1.add(jTextFieldApellido1);

        jLabel8.setText("Segundo Apellido");
        jPanel1.add(jLabel8);
        jPanel1.add(jTextFieldApellido2);

        jLabel4.setText("DNI");
        jPanel1.add(jLabel4);
        jPanel1.add(jTextFieldApellidoDNI);

        jLabel6.setText("Telefono");
        jPanel1.add(jLabel6);
        jPanel1.add(jTextFieldTelefono);

        jLabel5.setText("Email");
        jPanel1.add(jLabel5);
        jPanel1.add(jTextFieldEmail);

        jLabel7.setText("Fecha Alta");
        jPanel1.add(jLabel7);

        jSpinnerFechaAlta.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerFechaAlta.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFechaAlta, "dd/MM/yy hh:mm"));
        jPanel1.add(jSpinnerFechaAlta);

        jLabel9.setText("Estado");
        jPanel1.add(jLabel9);

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alta", "Baja", "Suspendido" }));
        jPanel1.add(jComboBoxEstado);

        jButtonAlta.setText("Alta");
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });

        jButtonCerrar.setText("Cancelar");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jButtonAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCerrar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlta)
                    .addComponent(jButtonCerrar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
        // TODO add your handling code here:
        Socio nuevo = new Socio(
            jTextFieldNombre.getText(),
            jTextFieldApellido1.getText(),
            jTextFieldApellido2.getText(),
            jTextFieldApellidoDNI.getText(),
            jTextFieldTelefono.getText(),
            jTextFieldEmail.getText(),
            (Date)jSpinnerFechaAlta.getValue(),
            jComboBoxEstado.getSelectedItem().toString()
        );
        jframepadre.addSocio(nuevo);
        
        // TERMINAR
        
        try {
            PreparedStatement ps = conexion.prepareStatement(
                "INSERT INTO socio (Nombre, Apellido1, Apellido2, DNI, Telefono, Correo, Fecha_Alta, Estado) " +
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?)"
            );

            ps.setString(1, nuevo.getNombre());
            ps.setString(2, nuevo.getApellido1());
            ps.setString(3, nuevo.getApellido2());
            ps.setString(4, nuevo.getDni());
            ps.setString(5, nuevo.getTelefono());
            ps.setString(6, nuevo.getCorreo());
            ps.setDate(7, new java.sql.Date(nuevo.getFecha_alta().getTime()));
            ps.setString(8, nuevo.getEstado());

            ps.executeUpdate(); // Ejecuta el INSERT
            ps.close();

        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(JFrameGestionSocios.class.getName())
                .log(java.util.logging.Level.SEVERE, "Error al insertar socio en la BD", ex);
        }
        
        dispose();
    }//GEN-LAST:event_jButtonAltaActionPerformed
    
    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new JDialogAltaCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerFechaAlta;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldApellido2;
    private javax.swing.JTextField jTextFieldApellidoDNI;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
