/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import java.sql.Connection;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
/**
 *
 * @author DAM2Alu14
 */
public class JDialogEditarUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogEditarUsuario.class.getName());


    // TERMINAR NO HACE FALTA INTRODUCIR LA CONTRASEPÑA ACTUAL
    
    /**
     * Creates new form JDialogAltaCliente
     */
    Connection conexion; // conexión pública
    private int idUsuario;
    JFrameUsuarios jframepadre; // referencia al JFrameUsuarios padre

    
    public JDialogEditarUsuario(JFrameUsuarios padre, Connection conexion, int idUsuario) {
        this.jframepadre = padre;
        this.conexion = conexion;
        this.idUsuario = idUsuario;
        initComponents();
        cargarUsuario(); // carga los datos actuales
    }

    // METODO
    public void cargarUsuario() {
       try {
            String sql = "SELECT Plan_ID, Usuario, Contrasena, Rol FROM usuario WHERE ID_Usuario=?";
            PreparedStatement ps = conexion.prepareStatement(sql);
            ps.setInt(1, idUsuario);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                jTextFieldPlanID.setText(String.valueOf(rs.getInt("Plan_ID")));
                jTextFieldUsuario.setText(rs.getString("Usuario"));
                jPasswordNueva.setText("");
                jPasswordConfirmar.setText("");
                jComboBoxRol.setSelectedItem(rs.getString("Rol"));
            }

            rs.close();
            ps.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error cargando usuario: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPlanID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordNueva = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordConfirmar = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxRol = new javax.swing.JComboBox<>();
        jButtonEditar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("EDITAR CLIENTES");

        jPanel1.setLayout(new java.awt.GridLayout(6, 2, 10, 10));

        jLabel2.setText("Plan_ID");
        jPanel1.add(jLabel2);
        jPanel1.add(jTextFieldPlanID);

        jLabel11.setText("Usuario");
        jPanel1.add(jLabel11);
        jPanel1.add(jTextFieldUsuario);

        jLabel8.setText("Nueva Contraseña");
        jPanel1.add(jLabel8);
        jPanel1.add(jPasswordNueva);

        jLabel4.setText("Confirmar Contraseña");
        jPanel1.add(jLabel4);
        jPanel1.add(jPasswordConfirmar);

        jLabel12.setText("Rol");
        jPanel1.add(jLabel12);

        jComboBoxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrenador", "Administrador", "Profesor" }));
        jPanel1.add(jComboBoxRol);

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEditar)
                .addGap(30, 30, 30)
                .addComponent(jButtonCancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonCancelar))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        String usuario = jTextFieldUsuario.getText().trim();
        String planIDStr = jTextFieldPlanID.getText().trim();
        String rol = jComboBoxRol.getSelectedItem().toString();

        if (usuario.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El Usuario es obligatorio.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            Integer planID = null;
            if (!planIDStr.isEmpty()) {
                planID = Integer.parseInt(planIDStr);
            }

            // Verificar si se quiere cambiar la contraseña
            String nueva = new String(jPasswordNueva.getPassword());
            String confirmar = new String(jPasswordConfirmar.getPassword());
            String contrasenaFinal = null;

            // Si alguno de los campos de contraseña tiene contenido
            if (!nueva.isEmpty() || !confirmar.isEmpty()) {
                // Ambos deben estar completos
                if (nueva.isEmpty() || confirmar.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Para cambiar la contraseña debe completar ambos campos de contraseña.", "Error", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                // Verificar que coincidan
                if (!nueva.equals(confirmar)) {
                    JOptionPane.showMessageDialog(this, "La nueva contraseña y la confirmación no coinciden.", "Error", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                contrasenaFinal = nueva;
            }

            // Preparar actualización
            String sql = "UPDATE usuario SET Plan_ID=?, Usuario=?, Rol=?" +
                         (contrasenaFinal != null ? ", Contrasena=?" : "") +
                         " WHERE ID_Usuario=?";
            PreparedStatement ps = conexion.prepareStatement(sql);
            
            if (planID != null) {
                ps.setInt(1, planID);
            } else {
                ps.setNull(1, java.sql.Types.INTEGER);
            }
            
            ps.setString(2, usuario);
            ps.setString(3, rol);
            int paramIndex = 4;
            if (contrasenaFinal != null) {
                ps.setString(4, contrasenaFinal);
                paramIndex++;
            }
            ps.setInt(paramIndex, idUsuario);

            ps.executeUpdate();
            ps.close();

            JOptionPane.showMessageDialog(this, "Usuario actualizado correctamente.");
            jframepadre.cargaUsuariosBD(); // refrescar tabla en el padre
            dispose();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Plan_ID debe ser un número válido.", "Error", JOptionPane.WARNING_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al actualizar usuario: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new JDialogAltaCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JComboBox<String> jComboBoxRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordConfirmar;
    private javax.swing.JPasswordField jPasswordNueva;
    private javax.swing.JTextField jTextFieldPlanID;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
