/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import java.sql.Connection;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
/**
 *
 * @author DAM2Alu14
 */
public class JDialogEditarUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogEditarUsuario.class.getName());
    
    /**
     * Creates new form JDialogAltaCliente
     */
    Connection conexion;
    JFrameUsuarios jframepadre;
    private Usuario usuario;
    
    // Carga los ids disponibles en el jComboBoxId
    public void cargaID() {
        jComboBoxId.removeAllItems();
        for (Usuario u : LogicaUsuarios.getUsuarios()) {
            jComboBoxId.addItem(String.valueOf(u.getId_usuario()));
        }
    }
    
    public void cargarCampos(Usuario usuario) {
        jComboBoxId.setSelectedItem(String.valueOf(usuario.getId_usuario()));
        jSpinnerPlanId.setValue(usuario.getPlan_id());
        jTextFieldNombreUsuario.setText(usuario.getNombre_usuario());
        jPasswordFieldContrasena.setText(usuario.getContrasena());
        jComboBoxRol.setSelectedItem(usuario.getRol());
    }
    
    public JDialogEditarUsuario(java.awt.Frame parent, boolean modal, Connection conexion, Usuario usuario) {
        jframepadre = (JFrameUsuarios)parent;
        initComponents();
        this.conexion = conexion;
        this.usuario = usuario;
        cargaID();
        
        // Cargar los datos del usuario seleccionado
        cargarCampos(usuario);
    }

    // METODOS
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxId = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerPlanId = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldNombreUsuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordFieldContrasena = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxRol = new javax.swing.JComboBox<>();
        jButtonEditar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("EDITAR CLIENTES");

        jPanel1.setLayout(new java.awt.GridLayout(5, 2, 10, 10));

        jLabel3.setText("ID Usuario");
        jPanel1.add(jLabel3);

        jComboBoxId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxIdItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBoxId);

        jLabel2.setText("Plan_ID");
        jPanel1.add(jLabel2);
        jPanel1.add(jSpinnerPlanId);

        jLabel11.setText("Usuario");
        jPanel1.add(jLabel11);
        jPanel1.add(jTextFieldNombreUsuario);

        jLabel8.setText("Nueva Contraseña");
        jPanel1.add(jLabel8);
        jPanel1.add(jPasswordFieldContrasena);

        jLabel12.setText("Rol");
        jPanel1.add(jLabel12);

        jComboBoxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrenador", "Administrador", "Profesor" }));
        jPanel1.add(jComboBoxRol);

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEditar)
                .addGap(30, 30, 30)
                .addComponent(jButtonCancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonCancelar))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        int id = Integer.parseInt(jComboBoxId.getSelectedItem().toString());
        int planId = (Integer) jSpinnerPlanId.getValue();
        String nombreUsuario = jTextFieldNombreUsuario.getText().trim();
        String contrasena = new String(jPasswordFieldContrasena.getPassword()).trim();
        String rol = jComboBoxRol.getSelectedItem().toString().trim();

        // Comprobar que los campos obligatorios no estén vacíos
        if (nombreUsuario.isEmpty() ||
            contrasena.isEmpty() ||
            rol.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Todos los campos obligatorios deben estar llenos.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // Comprobar si el nombre de usuario ya está registrado en otro usuario
        try {
            PreparedStatement psCheck = conexion.prepareStatement(
                "SELECT COUNT(*) FROM usuario WHERE Usuario = ? AND ID_Usuario <> ?"
            );
            psCheck.setString(1, nombreUsuario);
            psCheck.setInt(2, id);

            java.sql.ResultSet rs = psCheck.executeQuery();
            rs.next();
            int existe = rs.getInt(1);

            rs.close();
            psCheck.close();

            if (existe > 0) {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "El nombre de usuario " + nombreUsuario + " ya está registrado en otro usuario.",
                    "Usuario duplicado",
                    javax.swing.JOptionPane.WARNING_MESSAGE
                );
                return;
            }

        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error al comprobar nombre de usuario", ex);
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Error al verificar nombre de usuario en la base de datos.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // Editar el usuario con los datos ingresados
        Usuario usuarioEditar = LogicaUsuarios.getUsuario(id);
        usuarioEditar.setPlan_id(planId);
        usuarioEditar.setNombre_usuario(nombreUsuario);
        usuarioEditar.setContrasena(contrasena);
        usuarioEditar.setRol(rol);

        // Actualizar en LogicaUsuarios
        LogicaUsuarios.editUsuario(usuarioEditar);

        try {
            // Actualizar en BBDD
            PreparedStatement ps = conexion.prepareStatement(
                "UPDATE usuario SET Plan_ID = ?, Usuario = ?, Contrasena = ?, Rol = ? WHERE ID_Usuario = ?"
            );

            ps.setInt(1, planId);
            ps.setString(2, usuarioEditar.getNombre_usuario());
            ps.setString(3, usuarioEditar.getContrasena());
            ps.setString(4, usuarioEditar.getRol());
            ps.setInt(5, id);

            ps.executeUpdate();
            ps.close();

        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error al actualizar usuario", ex);
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Error al actualizar el usuario en la base de datos.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // Refrescar tabla desde LogicaUsuarios y cerrar ventana
        jframepadre.actualizarTabla();
        dispose();
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jComboBoxIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxIdItemStateChanged
        // TODO add your handling code here:
        if (jComboBoxId.getSelectedItem() != null) {
            int id = Integer.parseInt(jComboBoxId.getSelectedItem().toString());
            Usuario u = LogicaUsuarios.getUsuario(id);
            if (u != null) {
                jSpinnerPlanId.setValue(u.getPlan_id());
                jTextFieldNombreUsuario.setText(u.getNombre_usuario());
                jPasswordFieldContrasena.setText(u.getContrasena());
                jComboBoxRol.setSelectedItem(u.getRol());
            }
        }
    }//GEN-LAST:event_jComboBoxIdItemStateChanged
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new JDialogAltaCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JComboBox<String> jComboBoxId;
    private javax.swing.JComboBox<String> jComboBoxRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldContrasena;
    private javax.swing.JSpinner jSpinnerPlanId;
    private javax.swing.JTextField jTextFieldNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
