/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import ConexionBBDD.ConexionBBDD;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author DAM2Alu14
 */
public class JDialogAltaUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogAltaUsuario.class.getName());

    
    /**
     * Creates new form JDialogAltaCliente
     */
    Connection conexion;
    JFrameUsuarios jframepadre;
    
    public JDialogAltaUsuario(java.awt.Frame parent, boolean modal, Connection conexionPadre) {
        jframepadre = (JFrameUsuarios)parent;
        initComponents();
        this.conexion = conexionPadre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerPlanId = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNombreUsuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordFieldContrasena = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxRol = new javax.swing.JComboBox<>();
        jButtonAlta = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("ALTA USUARIOS");

        jPanel1.setLayout(new java.awt.GridLayout(4, 2, 10, 10));

        jLabel2.setText("Plan_ID");
        jPanel1.add(jLabel2);
        jPanel1.add(jSpinnerPlanId);

        jLabel3.setText("Usuario");
        jPanel1.add(jLabel3);
        jPanel1.add(jTextFieldNombreUsuario);

        jLabel8.setText("Nueva Contraseña");
        jPanel1.add(jLabel8);
        jPanel1.add(jPasswordFieldContrasena);

        jLabel6.setText("Rol");
        jPanel1.add(jLabel6);

        jComboBoxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrenador", "Administrador", "Profesor" }));
        jPanel1.add(jComboBoxRol);

        jButtonAlta.setText("Alta");
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });

        jButtonCerrar.setText("Cancelar");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jButtonAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCerrar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlta)
                    .addComponent(jButtonCerrar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
      // Obtener datos del formulario
      String nombreUsuario = jTextFieldNombreUsuario.getText().trim();
      String contrasena = new String(jPasswordFieldContrasena.getPassword()).trim();
      String rol = jComboBoxRol.getSelectedItem().toString().trim();
      int planId = (Integer) jSpinnerPlanId.getValue();

      // Comprobar campos obligatorios
      if (nombreUsuario.isEmpty() ||
          contrasena.isEmpty() ||
          rol.isEmpty()) {

          JOptionPane.showMessageDialog(
              this,
              "Todos los campos obligatorios deben estar llenos.",
              "Error",
              JOptionPane.ERROR_MESSAGE
          );
          return;
      }

      try {
          // Comprobar si el nombre de usuario ya existe
          PreparedStatement psCheck = conexion.prepareStatement(
              "SELECT COUNT(*) FROM usuario WHERE Usuario = ?"
          );
          psCheck.setString(1, nombreUsuario);

          ResultSet rs = psCheck.executeQuery();
          rs.next();
          int existe = rs.getInt(1);

          rs.close();
          psCheck.close();

          // Avisar si el usuario ya está registrado
          if (existe > 0) {
              JOptionPane.showMessageDialog(
                  this,
                  "El usuario " + nombreUsuario + " ya está registrado.",
                  "Usuario duplicado",
                  JOptionPane.WARNING_MESSAGE
              );
              return;
          }

          // Crear usuario
          Usuario nuevoUsuario = new Usuario(
              planId,
              nombreUsuario,
              contrasena,
              rol
          );


          // Insertar el usuario en la base de datos
          PreparedStatement ps = conexion.prepareStatement(
              "INSERT INTO usuario (Plan_ID, Usuario, Contrasena, Rol) VALUES (?, ?, ?, ?)"
          );
          
          ps.setInt(1, planId);
          ps.setString(2, nuevoUsuario.getNombre_usuario());
          ps.setString(3, nuevoUsuario.getContrasena());
          ps.setString(4, nuevoUsuario.getRol());

          ps.executeUpdate();
          ps.close();

          // Obtener el último ID insertado
          int nuevoId = -1;
          PreparedStatement psId = conexion.prepareStatement(
              "SELECT MAX(id_usuario) FROM usuario"
          );
          ResultSet rsId = psId.executeQuery();

          if (rsId.next()) {
              nuevoId = rsId.getInt(1);
          }

          rsId.close();
          psId.close();

          nuevoUsuario.setId_usuario(nuevoId);
          LogicaUsuarios.addUsuario(nuevoUsuario);
          jframepadre.actualizarTabla();
          dispose();

      } catch (SQLException ex) {
          logger.log(java.util.logging.Level.SEVERE, "Error al verificar o insertar usuario", ex);

          JOptionPane.showMessageDialog(
              this,
              "Error en la base de datos.",
              "Error",
              JOptionPane.ERROR_MESSAGE
          );
      }
    }//GEN-LAST:event_jButtonAltaActionPerformed
    
    
    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new JDialogAltaCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JComboBox<String> jComboBoxRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldContrasena;
    private javax.swing.JSpinner jSpinnerPlanId;
    private javax.swing.JTextField jTextFieldNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
