/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import java.sql.Connection;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.SwingConstants;

/**
 *
 * @author DAM2Alu9
 */
public class JFrameMenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameMenuPrincipal.class.getName());
    
    private String rol;
    

    /**
     * Creates new form JFrameMenuPrincipal
     */
    public JFrameMenuPrincipal(String rol) {
        this.rol = rol;
        initComponents();
        setLocationRelativeTo(null);
        icono1();
        icono2();
        icono3();
        icono4();
        icono5();
        icono6();
        icono7();
        icono8();
        
        configurarBotones(jButtonAsistencias);
        configurarBotones(jButtonAyuda);
        configurarBotones(jButtonCerrarSesion);
        configurarBotones(jButtonPagos);
        configurarBotones(jButtonPlanes);
        configurarBotones(jButtonSocios);
        configurarBotones(jButtonUsuarios);
        configurarMenu();
    }
    
    
    
    public void icono1(){
        //PROBLEMA LAS IMAGENES SE UBICAN EN BUILD/CLASSES/IMAGENES, NO ESTA EN GITHUB
         ImageIcon original = new ImageIcon(getClass().getResource("/imagenes/logo_GymManager.png"));
        Image imagenEscalada = original.getImage().getScaledInstance(jLabelTitulo.getWidth(), jLabelTitulo.getHeight(), Image.SCALE_SMOOTH);
        jLabelTitulo.setIcon(new ImageIcon(imagenEscalada));
    }
    
    public void icono2(){
        ImageIcon original = new ImageIcon(getClass().getResource("/imagenes/avatar.png"));
        Image imagenEscalada = original.getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH);
        jButtonSocios.setIcon(new ImageIcon(imagenEscalada));
    }
    
    public void icono3(){
        ImageIcon original = new ImageIcon(getClass().getResource("/imagenes/credit-cards-payment.png"));
        Image imagenEscalada = original.getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH);
        jButtonPagos.setIcon(new ImageIcon(imagenEscalada));
    }
    
    public void icono4(){
        ImageIcon original = new ImageIcon(getClass().getResource("/imagenes/available.png"));
        Image imagenEscalada = original.getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH);
        jButtonAsistencias.setIcon(new ImageIcon(imagenEscalada));
    }
    
    public void icono5(){
        ImageIcon original = new ImageIcon(getClass().getResource("/imagenes/weight.png"));
        Image imagenEscalada = original.getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH);
        jButtonPlanes.setIcon(new ImageIcon(imagenEscalada));
    }
    
    public void icono6(){
        ImageIcon original = new ImageIcon(getClass().getResource("/imagenes/avatar.png"));
        Image imagenEscalada = original.getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH);
        jButtonUsuarios.setIcon(new ImageIcon(imagenEscalada));
    }
    public void icono7(){
        ImageIcon original = new ImageIcon(getClass().getResource("/imagenes/simbolo ayuda.png"));
        Image imagenEscalada = original.getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH);
        jButtonAyuda.setIcon(new ImageIcon(imagenEscalada));
    }
    public void icono8(){
        ImageIcon original = new ImageIcon(getClass().getResource("/imagenes/logout.png"));
        Image imagenEscalada = original.getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH);
        jButtonCerrarSesion.setIcon(new ImageIcon(imagenEscalada));
    }
    
    private void configurarBotones(JButton b){
        b.setHorizontalAlignment(SwingConstants.LEFT);
        b.setHorizontalTextPosition(SwingConstants.RIGHT);
        b.setIconTextGap(10);
        b.setFocusPainted(false);
        b.setBorderPainted(false);
        b.setContentAreaFilled(false);
        b.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jPanelLateral = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonSocios = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonPagos = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jButtonAsistencias = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jButtonPlanes = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jButtonUsuarios = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jButtonAyuda = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        jButtonCerrarSesion = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelLateral.setBackground(new java.awt.Color(153, 153, 153));
        jPanelLateral.setPreferredSize(new java.awt.Dimension(220, 415));
        jPanelLateral.setLayout(new javax.swing.BoxLayout(jPanelLateral, javax.swing.BoxLayout.Y_AXIS));

        jLabelTitulo.setText("GYM MANAGER");
        jLabelTitulo.setMaximumSize(new java.awt.Dimension(220, 80));
        jLabelTitulo.setMinimumSize(new java.awt.Dimension(120, 16));
        jLabelTitulo.setName(""); // NOI18N
        jPanelLateral.add(jLabelTitulo);

        jSeparator1.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanelLateral.add(jSeparator1);

        jButtonSocios.setBackground(new java.awt.Color(153, 153, 153));
        jButtonSocios.setText("Socios");
        jButtonSocios.setActionCommand("");
        jButtonSocios.setAlignmentY(0.0F);
        jButtonSocios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonSocios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonSocios.setIconTextGap(10);
        jButtonSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSociosActionPerformed(evt);
            }
        });
        jPanelLateral.add(jButtonSocios);

        jSeparator2.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanelLateral.add(jSeparator2);

        jButtonPagos.setBackground(new java.awt.Color(153, 153, 153));
        jButtonPagos.setText("Pagos");
        jButtonPagos.setActionCommand("");
        jButtonPagos.setAlignmentY(0.0F);
        jButtonPagos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonPagos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonPagos.setIconTextGap(10);
        jButtonPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagosActionPerformed(evt);
            }
        });
        jPanelLateral.add(jButtonPagos);

        jSeparator3.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanelLateral.add(jSeparator3);

        jButtonAsistencias.setBackground(new java.awt.Color(153, 153, 153));
        jButtonAsistencias.setText("Asistencias");
        jButtonAsistencias.setActionCommand("");
        jButtonAsistencias.setAlignmentY(0.0F);
        jButtonAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsistenciasActionPerformed(evt);
            }
        });
        jPanelLateral.add(jButtonAsistencias);

        jSeparator4.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanelLateral.add(jSeparator4);

        jButtonPlanes.setBackground(new java.awt.Color(153, 153, 153));
        jButtonPlanes.setText("Planes de Entrenamiento");
        jButtonPlanes.setActionCommand("");
        jButtonPlanes.setAlignmentY(0.0F);
        jButtonPlanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlanesActionPerformed(evt);
            }
        });
        jPanelLateral.add(jButtonPlanes);

        jSeparator5.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanelLateral.add(jSeparator5);

        jButtonUsuarios.setBackground(new java.awt.Color(153, 153, 153));
        jButtonUsuarios.setText("Usuarios");
        jButtonUsuarios.setActionCommand("");
        jButtonUsuarios.setAlignmentY(0.0F);
        jPanelLateral.add(jButtonUsuarios);

        jSeparator7.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanelLateral.add(jSeparator7);

        jButtonAyuda.setBackground(new java.awt.Color(153, 153, 153));
        jButtonAyuda.setText("Ayuda");
        jButtonAyuda.setActionCommand("");
        jButtonAyuda.setAlignmentY(0.0F);
        jPanelLateral.add(jButtonAyuda);

        jSeparator8.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanelLateral.add(jSeparator8);

        jButtonCerrarSesion.setBackground(new java.awt.Color(153, 153, 153));
        jButtonCerrarSesion.setText("Cerrar Sesión");
        jButtonCerrarSesion.setActionCommand("");
        jButtonCerrarSesion.setAlignmentY(0.0F);
        jPanelLateral.add(jButtonCerrarSesion);

        getContentPane().add(jPanelLateral, java.awt.BorderLayout.WEST);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSociosActionPerformed
        // TODO add your handling code here:
        JFrameGestionSocios ventanaSocios = new JFrameGestionSocios(rol);
        ventanaSocios.setVisible(true);
        ventanaSocios.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_jButtonSociosActionPerformed

    private void jButtonAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsistenciasActionPerformed
        // TODO add your handling code here:
        
        JFrameGestionAsistencias asistencias = new JFrameGestionAsistencias(rol);
        asistencias.setVisible(true);
        asistencias.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonAsistenciasActionPerformed

    private void jButtonPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagosActionPerformed
        // TODO add your handling code here:
        JFramePagos pagos = new JFramePagos(rol);
        pagos.setVisible(true);
        pagos.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonPagosActionPerformed

    private void jButtonPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlanesActionPerformed
        // TODO add your handling code here:
        JFrameGestionPlanes planes = new JFrameGestionPlanes(rol);
        planes.setVisible(true);
        planes.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonPlanesActionPerformed

    
    public void configurarMenu() {
        // TERMINAR Profesor
        //if (rolUsuario == "Entrenador") {
        if (rol.equals("Entrenador")) {
            // Desactivar botones que NO deben usarse
            jButtonSocios.setEnabled(false);
            jButtonPagos.setEnabled(false);
            jButtonUsuarios.setEnabled(false);

            // Mantener activados los permitidos
            jButtonAsistencias.setEnabled(true);
            jButtonAyuda.setEnabled(true);
            jButtonCerrarSesion.setEnabled(true);
            jButtonPlanes.setEnabled(true);
        } else if(rol.equals("Administrador")){ // Es un admin
            // Mantener activados los permitidos
            jButtonSocios.setEnabled(true);
            jButtonPagos.setEnabled(true);
            jButtonUsuarios.setEnabled(true);
            jButtonAsistencias.setEnabled(true);
            jButtonAyuda.setEnabled(true);
            jButtonCerrarSesion.setEnabled(true);
            jButtonPlanes.setEnabled(true);
        } else { // Es un profesor
            // Desactivar botones que NO deben usarse
            jButtonSocios.setEnabled(false);
            jButtonPagos.setEnabled(false);
            jButtonUsuarios.setEnabled(false);
            jButtonPlanes.setEnabled(false);
            
            // Mantener activados los permitidos
            jButtonAsistencias.setEnabled(true);
            jButtonAyuda.setEnabled(true);
            jButtonCerrarSesion.setEnabled(true);
            
        }
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new JFrameMenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAsistencias;
    private javax.swing.JButton jButtonAyuda;
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonPagos;
    private javax.swing.JButton jButtonPlanes;
    private javax.swing.JButton jButtonSocios;
    private javax.swing.JButton jButtonUsuarios;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelLateral;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
