/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

/**
 *
 * @author DAM2Alu9
 */
public class JFrameMenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameMenuPrincipal.class.getName());

    /**
     * Creates new form JFrameMenuPrincipal
     */
    public JFrameMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        jPanelLateral = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonSocios = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonPagos = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jButtonAsistencias = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jButtonPlanes = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jButtonUsuarios = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jButtonAyuda = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        jButtonCerrarSesion = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelLateral.setBackground(new java.awt.Color(153, 153, 153));
        jPanelLateral.setPreferredSize(new java.awt.Dimension(220, 415));
        jPanelLateral.setLayout(new javax.swing.BoxLayout(jPanelLateral, javax.swing.BoxLayout.Y_AXIS));

        jLabelTitulo.setText("GYM MANAGER  ");
        jPanelLateral.add(jLabelTitulo);
        jPanelLateral.add(jSeparator1);

        jButtonSocios.setBackground(new java.awt.Color(153, 153, 153));
        jButtonSocios.setText("Socios");
        jButtonSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSociosActionPerformed(evt);
            }
        });
        jPanelLateral.add(jButtonSocios);
        jPanelLateral.add(jSeparator2);

        jButtonPagos.setText("Pagos");
        jPanelLateral.add(jButtonPagos);
        jPanelLateral.add(jSeparator3);

        jButtonAsistencias.setText("Asistencias");
        jPanelLateral.add(jButtonAsistencias);
        jPanelLateral.add(jSeparator4);

        jButtonPlanes.setText("Planes de Entrenamiento");
        jPanelLateral.add(jButtonPlanes);
        jPanelLateral.add(jSeparator5);

        jButtonUsuarios.setText("Usuarios");
        jPanelLateral.add(jButtonUsuarios);
        jPanelLateral.add(jSeparator7);

        jButtonAyuda.setText("Ayuda");
        jPanelLateral.add(jButtonAyuda);
        jPanelLateral.add(jSeparator8);

        jButtonCerrarSesion.setText("Cerrar Sesión");
        jPanelLateral.add(jButtonCerrarSesion);

        getContentPane().add(jPanelLateral, java.awt.BorderLayout.WEST);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSociosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSociosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameMenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAsistencias;
    private javax.swing.JButton jButtonAyuda;
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonPagos;
    private javax.swing.JButton jButtonPlanes;
    private javax.swing.JButton jButtonSocios;
    private javax.swing.JButton jButtonUsuarios;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelLateral;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    // End of variables declaration//GEN-END:variables
}
