/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import ConexionBBDD.ConexionBBDD;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.*;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author DAM2Alu14
 */
public class JFrameUsuarios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameUsuarios.class.getName());

    
    
    /**
     * Creates new form JFrameGestionSocios
     */
    DefaultTableModel dtm;
    ConexionBBDD nueva;
    Connection conexion;
    TableRowSorter<TableModel> order;
    
    private String rol;
    
    // --------------------------------------------------------------------------------------------------------------------------------
    // Carga usuario desde la base de datos
    // --------------------------------------------------------------------------------------------------------------------------------
    // Carga en la tabla los datos de la BBDD
    public void cargaUsuariosBD() {

        String sql = "SELECT ID_Usuario, Plan_ID, Usuario, Contrasena, Rol FROM usuario";

        try (PreparedStatement ps = conexion.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            dtm.setRowCount(0); // limpiar tabla

            while (rs.next()) {
                Object[] fila = new Object[5];
                fila[0] = rs.getInt("ID_Usuario");
                fila[1] = rs.getInt("Plan_ID");
                fila[2] = rs.getString("Usuario");
                fila[3] = rs.getString("Contrasena");
                fila[4] = rs.getString("Rol");

                dtm.addRow(fila);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                "Error cargando usuarios: " + ex.getMessage(),
                "Error BD", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // --------------------------------------------------------------------------------------------------------------------------------
        
    // CONSTRUCTOR
    public JFrameUsuarios(String rol) {
        this.rol = rol;
        initComponents();

        nueva = new ConexionBBDD();
        conexion = nueva.getConnection();
        dtm = new DefaultTableModel();
        jTableUsuarios.setModel(dtm);

        // Definir columnas de la tabla usuario
        String[] columnas = {"ID_Usuario", "Plan_ID", "Usuario", "Contraseña", "Rol"};
        dtm.setColumnIdentifiers(columnas);

        cargaUsuariosBD();

        order = new TableRowSorter<>(dtm);
        jTableUsuarios.setRowSorter(order);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButtonCargaUsuarios = new javax.swing.JButton();
        jButtonAlta = new javax.swing.JButton();
        jButtonBaja = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableUsuarios);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButtonCargaUsuarios.setText("Carga Usuarios");
        jButtonCargaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargaUsuariosActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCargaUsuarios);

        jButtonAlta.setText("Alta");
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAlta);

        jButtonBaja.setText("Baja");
        jButtonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonBaja);

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonEditar);

        jLabel1.setText("Buscar");
        jPanel3.add(jLabel1);

        jTextFieldBuscar.setPreferredSize(new java.awt.Dimension(80, 22));
        jTextFieldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarKeyReleased(evt);
            }
        });
        jPanel3.add(jTextFieldBuscar);

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonVolver);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        int fila = jTableUsuarios.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un usuario de la tabla");
            return;
        }

        int idUsuario = Integer.parseInt(jTableUsuarios.getValueAt(fila, 0).toString());

        // CREAR EDITAR USUARIO
        JDialogEditarUsuario dialog = new JDialogEditarUsuario(this, conexion, idUsuario);
        dialog.setVisible(true);

        cargaUsuariosBD(); // refrescar
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaActionPerformed
        if (jTableUsuarios.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un usuario.");
            return;
        }

        int fila = jTableUsuarios.getSelectedRow();
        int idUsuario = Integer.parseInt(jTableUsuarios.getValueAt(fila, 0).toString());

        try {
            PreparedStatement ps = conexion.prepareStatement("DELETE FROM usuario WHERE ID_Usuario = ?");
            ps.setInt(1, idUsuario);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Usuario eliminado correctamente");

            cargaUsuariosBD();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al eliminar usuario: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonBajaActionPerformed

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
        // Crear altausuario
        JDialogAltaUsuario dialog = new JDialogAltaUsuario(this, true, conexion);
        dialog.setVisible(true);

        cargaUsuariosBD();
    }//GEN-LAST:event_jButtonAltaActionPerformed

    // METODOS
    private void jButtonCargaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargaUsuariosActionPerformed
        cargaUsuariosBD();
    }//GEN-LAST:event_jButtonCargaUsuariosActionPerformed

    private void jTextFieldBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarKeyReleased
        try {
            RowFilter<Object, Object> rf = RowFilter.regexFilter(jTextFieldBuscar.getText());
            order.setRowFilter(rf);
        } catch (PatternSyntaxException e) {
            System.out.println("Patrón inválido");
        }
    }//GEN-LAST:event_jTextFieldBuscarKeyReleased

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // Cierra la ventana actual y abre el MenuPrincipal
        JFrameMenuPrincipal jfmp = new JFrameMenuPrincipal(rol);
        jfmp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    // METODOS
    public void cargarUsuarios() {
        String sql = "SELECT ID_Usuario, Plan_ID, Usuario, Contrasena, Rol FROM usuario";

        try (PreparedStatement ps = conexion.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            dtm.setRowCount(0); // limpiar tabla

            while (rs.next()) {
                Object[] fila = new Object[]{
                    rs.getInt("ID_Usuario"),
                    rs.getInt("Plan_ID"),
                    rs.getString("Usuario"),
                    rs.getString("Contrasena"),
                    rs.getString("Rol")
                };
                dtm.addRow(fila);
            }

        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error al cargar usuarios", ex);
            JOptionPane.showMessageDialog(
                this,
                "Error cargando usuarios desde la base de datos",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameUsuarios("Administrador").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonBaja;
    private javax.swing.JButton jButtonCargaUsuarios;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuarios;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
