/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import ConexionBBDD.ConexionBBDD;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.*;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author DAM2Alu14
 */
public class JFrameGestionSocios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameGestionSocios.class.getName());

    /**
     * Creates new form JFrameGestionSocios
     */
    DefaultTableModel dtm;
    ConexionBBDD nueva;
    Connection conexion;
    TableRowSorter<TableModel> order;
    
    private String rol;
    // --------------------------------------------------------------------------------------------------------------------------------
    
    // Carga en la tabla los datos de la BBDD
    public void cargaReal() {
        String sql = "SELECT Nombre, Apellido1, Apellido2, DNI, Telefono, Correo, Fecha_Alta, Estado FROM socio";

        try (PreparedStatement ps = conexion.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            dtm.setRowCount(0); // Borra filas existentes

            while (rs.next()) {
                Object[] fila = new Object[8];
                fila[0] = rs.getString("Nombre");
                fila[1] = rs.getString("Apellido1");
                fila[2] = rs.getString("Apellido2");
                fila[3] = rs.getString("DNI");
                fila[4] = rs.getString("Telefono");
                fila[5] = rs.getString("Correo");
                fila[6] = rs.getDate("Fecha_Alta");
                fila[7] = rs.getString("Estado");

                dtm.addRow(fila);
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    // Carga en la tabla visualmente los socios guardados en el array
    public void cargaInicial() { dtm.setRowCount(0); for (Socio socio: LogicaNegocio.getSocios()) { dtm.addRow(socio.devuelveFila()); } }
    
    // --------------------------------------------------------------------------------------------------------------------------------
        
    // CONSTRUCTOR
    public JFrameGestionSocios(String rol) {
        this.rol = rol;
        initComponents();

        // Inicializar conexión y modelo
        nueva = new ConexionBBDD();
        conexion = nueva.getConnection();
        dtm = new DefaultTableModel();
        jTableSocios.setModel(dtm);

        // Definir columnas
        String[] columnas = {"Nombre", "Apellido1", "Apellido2", "DNI", "Telefono", "Correo", "Fecha_Alta", "Estado"};
        dtm.setColumnIdentifiers(columnas);

        // Cargar datos desde la BBDD
        LogicaNegocio.cargaPrueba(); // Carga los datos de la bbdd en un array
        cargaReal(); // Carga los datos de la bbdd en la tabla
        order = new TableRowSorter<>(dtm);
        jTableSocios.setRowSorter(order);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSocios = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButtonCargaClientes = new javax.swing.JButton();
        jButtonAlta = new javax.swing.JButton();
        jButtonBaja = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableSocios);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButtonCargaClientes.setText("Carga Clientes");
        jButtonCargaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargaClientesActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCargaClientes);

        jButtonAlta.setText("Alta");
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAlta);

        jButtonBaja.setText("Baja");
        jButtonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonBaja);

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonEditar);

        jLabel1.setText("Buscar");
        jPanel3.add(jLabel1);

        jTextFieldBuscar.setPreferredSize(new java.awt.Dimension(80, 22));
        jTextFieldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarKeyReleased(evt);
            }
        });
        jPanel3.add(jTextFieldBuscar);

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonVolver);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        int fila = jTableSocios.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un socio de la tabla");
            return;
        }
        LogicaNegocio.cargaPrueba();
        // Obtener el ID desde LogicaNegocio (misma posición)
        Socio socioSeleccionado = LogicaNegocio.getSocios().get(fila);

        // Pasar el socio al JDialog
        JDialogEditarSocio jdec = new JDialogEditarSocio(this, true, conexion, socioSeleccionado);

        jdec.setVisible(true);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaActionPerformed
        // FALTA ACTUALIZAR VISUALMENTE
        if (jTableSocios.getSelectedRowCount() > 0) {
            int[] seleccionados = jTableSocios.getSelectedRows();

            try {
                // Sentencia para actualizar estado
                PreparedStatement ps = conexion.prepareStatement(
                    "UPDATE socio SET estado = ? WHERE DNI = ?"
                );

                // Recorremos de atrás hacia adelante
                for (int i = seleccionados.length - 1; i >= 0; i--) {

                    // Obtener el ID del socio (asumo columna 0)
                    String dni = (
                        jTableSocios.getValueAt(seleccionados[i], 3).toString()
                    );

                    // Establecemos ESTADO = "Baja" (o el valor que uses)
                    ps.setString(1, "Baja");
                    ps.setString(2, dni);

                    // Ejecutar actualización
                    ps.executeUpdate();

                }

                ps.close();
                JOptionPane.showMessageDialog(this,
                    "Socio/s dado/s de baja correctamente.");
                
                cargaReal(); // Recargo los datos

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(
                    this,
                    "Error al dar de baja socio.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(
                this,
                "Seleccione al menos un socio para dar de baja.",
                "Aviso",
                JOptionPane.WARNING_MESSAGE
            );
        }

        /*
        BORRAR SOCIO, TERMINAR, PROBLEMA AL BORRAR SOCIO POR LA FK
        if (jTableSocios.getSelectedRowCount() > 0) {
            int[] seleccionados = jTableSocios.getSelectedRows();

            try {
                // Preparar sentencia SQL
                PreparedStatement ps = conexion.prepareStatement(
                    "DELETE FROM socio WHERE DNI = ?"
                );

                // Recorrer las filas seleccionadas (de atrás hacia adelante para no alterar índices)
                for (int i = seleccionados.length - 1; i >= 0; i--) {
                    // Obtener el ID_SOCIO desde la tabla (suponiendo que está en la columna 0)
                    String dni = jTableSocios.getValueAt(seleccionados[i], 3).toString();

                    // Asignar el parámetro en la consulta
                    ps.setString(1, dni);

                    // Ejecutar eliminación en BD
                    ps.executeUpdate();

                    // Eliminar también la fila del modelo
                    dtm.removeRow(seleccionados[i]);
                }

                ps.close();
                JOptionPane.showMessageDialog(this, "Socio/s eliminado/s correctamente.");

            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(JFrameGestionSocios.class.getName())
                .log(java.util.logging.Level.SEVERE, "Error al eliminar socio de la BD", ex);
                JOptionPane.showMessageDialog(this, "Error al eliminar socio: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Seleccione al menos un socio para eliminar.",
                "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        */

    }//GEN-LAST:event_jButtonBajaActionPerformed

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
        // TODO add your handling code here:
        JDialogAltaSocio jdac = new JDialogAltaSocio(this, true, this.conexion);
        jdac.setVisible(true);
        //jd.setUusrio("");
    }//GEN-LAST:event_jButtonAltaActionPerformed

    // METODOS
    private void jButtonCargaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargaClientesActionPerformed
        cargaReal();  // Solo recarga los datos de la BBDD
    }//GEN-LAST:event_jButtonCargaClientesActionPerformed

    private void jTextFieldBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarKeyReleased
        // TODO add your handling code here:
        try {
            RowFilter<Object, Object> rf = RowFilter.regexFilter(jTextFieldBuscar.getText());
            order.setRowFilter(rf);
        } catch (PatternSyntaxException pse) {
            System.out.println("Bad regex pattern");
        }
    }//GEN-LAST:event_jTextFieldBuscarKeyReleased

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
        JFrameMenuPrincipal jfap = new JFrameMenuPrincipal(rol);
        jfap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    public void addSocio(Socio s) {
        // Solo añade la fila visible (sin id_socio)
        dtm.addRow(new Object[]{
            s.getNombre(),
            s.getApellido1(),
            s.getApellido2(),
            s.getDni(),
            s.getTelefono(),
            s.getCorreo(),
            s.getFecha_alta(),
            s.getEstado()
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        // TERMINAR
        //java.awt.EventQueue.invokeLater(() -> new JFrameGestionSocios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonBaja;
    private javax.swing.JButton jButtonCargaClientes;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSocios;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
