/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.vista;

import java.sql.Connection;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import proyecto.logica.LogicaSocios;
import proyecto.modelo.Socio;

/**
 *
 * @author DAM2Alu14
 */
public class JDialogEditarSocio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogEditarSocio.class.getName());

    /**
     * Creates new form JDialogAltaCliente
     */
    Connection conexion;
    JFrameGestionSocios jframepadre;
    private Socio socio;
    
    // Carga los ids disponibles en el jComboBoxId
    public void cargaID(){
        jComboBoxId.removeAllItems();
        for (Socio s : LogicaSocios.getSocios()) {
            jComboBoxId.addItem(String.valueOf(s.getId_socio()));
        }
    }
    
    public void cargarCampos(Socio socio) {
        jComboBoxId.setSelectedItem(String.valueOf(socio.getId_socio()));
        jTextFieldNombre.setText(socio.getNombre());
        jTextFieldApellido1.setText(socio.getApellido1());
        jTextFieldApellido2.setText(socio.getApellido2());
        jTextFieldDNI.setText(socio.getDni());
        jTextFieldTelefono.setText(socio.getTelefono());
        jTextFieldEmail.setText(socio.getCorreo());
        jSpinnerFechaAlta.setValue(socio.getFecha_alta());
        jComboBoxEstado.setSelectedItem(socio.getEstado());
    }

    public JDialogEditarSocio(java.awt.Frame parent, boolean modal, Connection conexion, Socio socio) {
        jframepadre = (JFrameGestionSocios)parent;
        initComponents();
        this.conexion = conexion;
        this.socio = socio;
        cargaID();
        
        // Cargar los datos del socio seleccionado
        cargarCampos(socio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxId = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldApellido2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSpinnerFechaAlta = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jButtonEditar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("EDITAR CLIENTES");

        jPanel1.setLayout(new java.awt.GridLayout(9, 2, 10, 10));

        jLabel10.setText("ID");
        jPanel1.add(jLabel10);

        jComboBoxId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxIdItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBoxId);

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2);
        jPanel1.add(jTextFieldNombre);

        jLabel3.setText("Primer Apellido");
        jPanel1.add(jLabel3);
        jPanel1.add(jTextFieldApellido1);

        jLabel8.setText("Segundo Apellido");
        jPanel1.add(jLabel8);
        jPanel1.add(jTextFieldApellido2);

        jLabel4.setText("DNI");
        jPanel1.add(jLabel4);
        jPanel1.add(jTextFieldDNI);

        jLabel6.setText("Telefono");
        jPanel1.add(jLabel6);
        jPanel1.add(jTextFieldTelefono);

        jLabel5.setText("Email");
        jPanel1.add(jLabel5);
        jPanel1.add(jTextFieldEmail);

        jLabel7.setText("Fecha Alta");
        jPanel1.add(jLabel7);

        jSpinnerFechaAlta.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerFechaAlta.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFechaAlta, "dd/MM/yy hh:mm"));
        jPanel1.add(jSpinnerFechaAlta);

        jLabel9.setText("Estado");
        jPanel1.add(jLabel9);

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alta", "Baja", "Suspendido" }));
        jPanel1.add(jComboBoxEstado);

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEditar)
                .addGap(30, 30, 30)
                .addComponent(jButtonCancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonCancelar))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        int id = Integer.parseInt(jComboBoxId.getSelectedItem().toString());
        String estado = (jComboBoxEstado.getSelectedItem().toString());

        // Comprobar que los campos obligatorios no estén vacíos
        if (jTextFieldNombre.getText().trim().isEmpty() ||
            jTextFieldApellido1.getText().trim().isEmpty() ||
            jTextFieldDNI.getText().trim().isEmpty() ||
            jTextFieldTelefono.getText().trim().isEmpty() ||
            jTextFieldEmail.getText().trim().isEmpty() ||
            jSpinnerFechaAlta.getValue() == null) {

            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Todos los campos obligatorios deben estar llenos.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // Comprobar si el DNI ya está registrado en otro socio
        String nuevoDNI = jTextFieldDNI.getText().trim();
        try {

            PreparedStatement psCheck = conexion.prepareStatement(
                "SELECT COUNT(*) FROM socio WHERE DNI = ? AND id_socio <> ?"
            );
            psCheck.setString(1, nuevoDNI);
            psCheck.setInt(2, id);

            java.sql.ResultSet rs = psCheck.executeQuery();
            rs.next();
            int existe = rs.getInt(1);

            rs.close();
            psCheck.close();

            if (existe > 0) {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "El DNI " + nuevoDNI + " ya está registrado en otro socio.",
                    "DNI duplicado",
                    javax.swing.JOptionPane.WARNING_MESSAGE
                );
                return;
            }

        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error al comprobar DNI", ex);
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Error al verificar DNI en la base de datos.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // Editar el socio con los datos ingresados
        Socio socio = LogicaSocios.getSocio(id);
        socio.setNombre(jTextFieldNombre.getText().trim());
        socio.setApellido1(jTextFieldApellido1.getText().trim());
        socio.setApellido2(jTextFieldApellido2.getText().trim());
        socio.setDni(nuevoDNI);
        socio.setTelefono(jTextFieldTelefono.getText().trim());
        socio.setCorreo(jTextFieldEmail.getText().trim());
        socio.setFecha_alta((Date)jSpinnerFechaAlta.getValue());
        socio.setEstado(estado);

        // Actualizar en LogicaSocios
        LogicaSocios.editSocio(socio);

        try {
            // Actualizar en BBDD
            PreparedStatement ps = conexion.prepareStatement(
                "UPDATE socio SET Nombre = ?, Apellido1 = ?, Apellido2 = ?, DNI = ?, " +
                "Telefono = ?, Correo = ?, Fecha_Alta = ?, Estado = ? WHERE id_socio = ?"
            );

            ps.setString(1, socio.getNombre());
            ps.setString(2, socio.getApellido1());
            ps.setString(3, socio.getApellido2());
            ps.setString(4, socio.getDni());
            ps.setString(5, socio.getTelefono());
            ps.setString(6, socio.getCorreo());
            ps.setDate(7, new java.sql.Date(socio.getFecha_alta().getTime()));
            ps.setString(8, socio.getEstado());
            ps.setInt(9, id);

            ps.executeUpdate();
            ps.close();

        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error al actualizar socio", ex);
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Error al actualizar el socio en la base de datos.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        jframepadre.actualizarTabla();
        dispose();
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jComboBoxIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxIdItemStateChanged
        // TODO add your handling code here:
        if(jComboBoxId.getSelectedItem() != null) {
            int id = Integer.parseInt(jComboBoxId.getSelectedItem().toString());
            Socio s = LogicaSocios.getSocio(id);
            jTextFieldNombre.setText(s.getNombre());
            jTextFieldApellido1.setText(s.getApellido1());
            jTextFieldApellido2.setText(s.getApellido2());
            jTextFieldDNI.setText(s.getDni());
            jTextFieldTelefono.setText(s.getTelefono());
            jTextFieldEmail.setText(s.getCorreo());
            jSpinnerFechaAlta.setValue(s.getFecha_alta());          
            jComboBoxEstado.setSelectedItem(s.getEstado());
        }
    }//GEN-LAST:event_jComboBoxIdItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new JDialogAltaCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JComboBox<String> jComboBoxId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerFechaAlta;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldApellido2;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
