/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.vista;

import ConexionBBDD.ConexionBBDD;
import java.sql.*;
import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Date;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.export.ooxml.JRXlsxExporter;
import net.sf.jasperreports.export.SimpleExporterInput;
import net.sf.jasperreports.export.SimpleOutputStreamExporterOutput;
import net.sf.jasperreports.view.JasperViewer;
import proyecto.modelo.Plan;
import proyecto.logica.PlanDAO;

/**
 *
 * @author DAM2Alu9
 */
public class JFrameGestionPlanes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameGestionPlanes.class.getName());
    
    ConexionBBDD nueva;
    Connection conexion;
    
    PlanDAO dao = new PlanDAO();
    private javax.swing.table.TableRowSorter<DefaultTableModel> sorter;

    /**
     * Creates new form JFrameGestionPagos
     */
    private String rol;
    public JFrameGestionPlanes(String rol) {
        this.rol = rol;
        initComponents();
        
        nueva = new ConexionBBDD();
        conexion = nueva.getConnection();
        
        cargarTabla();
        
        DefaultTableModel model = (DefaultTableModel) jTablePlanes.getModel();
        sorter = new javax.swing.table.TableRowSorter<>(model);
        jTablePlanes.setRowSorter(sorter);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePlanes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonAgregar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jLabelBuscar = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTablePlanes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id_Plan", "Socio_ID", "Descripcion", "Fecha_Inicio", "Fecha_Fin"
            }
        ));
        jScrollPane1.setViewportView(jTablePlanes);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GESTIÓN DE PLANES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAgregar);

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEliminar);

        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonActualizar);

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonVolver);

        jLabelBuscar.setText("Buscar");
        jLabelBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabelBuscarKeyReleased(evt);
            }
        });
        jPanel2.add(jLabelBuscar);

        jTextFieldBuscar.setPreferredSize(new java.awt.Dimension(84, 22));
        jTextFieldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarKeyReleased(evt);
            }
        });
        jPanel2.add(jTextFieldBuscar);

        jButtonImprimir.setText("Imprimir Planes");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonImprimir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        String dni = JOptionPane.showInputDialog(this, "Introduce el DNI del socio:");
        if (dni == null || dni.trim().isEmpty()) return;

        int socioId = -1;
        String nombreSocio = "";
        try {
            PreparedStatement ps = conexion.prepareStatement(
                "SELECT id_socio, CONCAT(nombre,' ',apellido1) AS nombre FROM socio WHERE dni = ?"
            );
            ps.setString(1, dni.trim());
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                socioId = rs.getInt("id_socio");
                nombreSocio = rs.getString("nombre");
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró ningún socio con ese DNI");
                return;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al buscar socio: " + e.getMessage());
            return;
        }

        // Comprobar si el socio ya tiene un plan
        try {
            PreparedStatement check = conexion.prepareStatement(
                "SELECT COUNT(*) FROM plan WHERE Socio_ID = ?"
            );
            check.setInt(1, socioId);
            ResultSet rsCheck = check.executeQuery();
            rsCheck.next();
            if (rsCheck.getInt(1) > 0) {
                JOptionPane.showMessageDialog(null,
                    "El socio " + nombreSocio + " ya tiene un plan asignado");
                return;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al verificar plan existente: " + e.getMessage());
            return;
        }

        String descripcion = JOptionPane.showInputDialog(this,
            "Socio encontrado: " + nombreSocio + "\nIntroduce la descripción del plan:");
        if (descripcion == null || descripcion.trim().isEmpty()) return;

        String importeStr = JOptionPane.showInputDialog(this, "Importe del plan (ej: 30.00):");
        if (importeStr == null || importeStr.trim().isEmpty()) return;
        double importe;
        try {
            importe = Double.parseDouble(importeStr.replace(",", "."));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Importe inválido");
            return;
        }

        String fechaInicioStr = JOptionPane.showInputDialog(this, "Fecha de inicio (yyyy-MM-dd):");
        if (fechaInicioStr == null) return;

        String fechaFinStr = JOptionPane.showInputDialog(this, "Fecha de fin (yyyy-MM-dd):");
        if (fechaFinStr == null) return;

        Date fechaInicio = convertirFecha(fechaInicioStr);
        Date fechaFin = convertirFecha(fechaFinStr);
        if (fechaInicio == null || fechaFin == null) return;

        Plan plan = new Plan(0, socioId, descripcion, importe, fechaInicio, fechaFin);
        if (dao.insertar(plan)) {
            JOptionPane.showMessageDialog(null, "Plan agregado correctamente");
            cargarTabla();
        } else {
            JOptionPane.showMessageDialog(null, "Error al agregar el plan");
        }
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        int filaVista = jTablePlanes.getSelectedRow();

        if (filaVista == -1) {
            JOptionPane.showMessageDialog(null, "Selecciona un plan de la tabla primero");
            return;
        }

        int filaModelo = jTablePlanes.convertRowIndexToModel(filaVista);
        DefaultTableModel model = (DefaultTableModel) jTablePlanes.getModel();
        int idPlan = (int) model.getValueAt(filaModelo, 0);

        Plan planActual = dao.buscar(idPlan);
        if (planActual == null) {
            JOptionPane.showMessageDialog(null, "No se pudo encontrar el plan");
            return;
        }

        String nuevaDesc = JOptionPane.showInputDialog(this,
            "Nueva descripción:", planActual.getDescripcion());
        if (nuevaDesc == null || nuevaDesc.trim().isEmpty()) return;

        String importeStr = JOptionPane.showInputDialog(this,
            "Nuevo importe:", planActual.getImporte());
        if (importeStr == null || importeStr.trim().isEmpty()) return;
        double importe;
        try {
            importe = Double.parseDouble(importeStr.replace(",", "."));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Importe inválido");
            return;
        }

        String fechaInicioStr = JOptionPane.showInputDialog(this,
            "Nueva fecha de inicio (yyyy-MM-dd):", planActual.getFechaInicio().toString());
        if (fechaInicioStr == null) return;

        String fechaFinStr = JOptionPane.showInputDialog(this,
            "Nueva fecha de fin (yyyy-MM-dd):", planActual.getFechaFin().toString());
        if (fechaFinStr == null) return;

        Date fechaInicio = convertirFecha(fechaInicioStr);
        Date fechaFin = convertirFecha(fechaFinStr);
        if (fechaInicio == null || fechaFin == null) return;

        Plan planActualizado = new Plan(idPlan, planActual.getSocioId(), nuevaDesc, importe, fechaInicio, fechaFin);

        if (dao.actualizar(planActualizado)) {
            JOptionPane.showMessageDialog(null, "Plan actualizado correctamente");
            cargarTabla();
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo actualizar el plan");
        }
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        int[] filasVista = jTablePlanes.getSelectedRows();

        if (filasVista.length == 0) {
            JOptionPane.showMessageDialog(null, "Selecciona al menos un plan de la tabla");
            return;
        }

        int confirmar = JOptionPane.showConfirmDialog(null,
            "¿Seguro que quieres eliminar " + filasVista.length + " plan(es)?",
            "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (confirmar != JOptionPane.YES_OPTION) return;

        DefaultTableModel model = (DefaultTableModel) jTablePlanes.getModel();

        // Primero recogemos todos los IDs
        List<Integer> idsAEliminar = new ArrayList<>();
        for (int filaVista : filasVista) {
            int filaModelo = jTablePlanes.convertRowIndexToModel(filaVista);
            idsAEliminar.add((int) model.getValueAt(filaModelo, 0));
        }

        // Luego borramos
        int eliminados = 0;
        for (int idPlan : idsAEliminar) {
            if (dao.eliminar(idPlan)) eliminados++;
        }

        JOptionPane.showMessageDialog(null, eliminados + " plan(es) eliminado(s) correctamente");
        cargarTabla();
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
       JFrameMenuPrincipal menu = new JFrameMenuPrincipal(rol);
       menu.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jLabelBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabelBuscarKeyReleased
            // TODO add your handling code here:
    }//GEN-LAST:event_jLabelBuscarKeyReleased

    private void jTextFieldBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarKeyReleased
                               
        String texto = jTextFieldBuscar.getText().trim();

        if (texto.isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            try {
                sorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto));
            } catch (PatternSyntaxException e) {
                System.out.println("Patrón inválido");
            }
        }
    }//GEN-LAST:event_jTextFieldBuscarKeyReleased

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
            String fileJasper = "informes/planes.jrxml";
            try{
                JasperReport report = JasperCompileManager.compileReport(fileJasper);
                JasperPrint print
                        = JasperFillManager.fillReport(report, null, nueva.getConnection());
                JasperExportManager.exportReportToPdfFile(print, "informes\\planes.pdf");
                JRXlsxExporter exporter = new JRXlsxExporter();
                exporter.setExporterInput(new SimpleExporterInput(print));
                exporter.setExporterOutput(new SimpleOutputStreamExporterOutput("informes\\planes.xlsx"));
                exporter.exportReport();
                JasperViewer.viewReport(print, false);

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null,"Se produjo un error al leer el archivo .jrxml");
            }
    }//GEN-LAST:event_jButtonImprimirActionPerformed


    private void cargarTabla() {
        DefaultTableModel model = (DefaultTableModel) jTablePlanes.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new String[]{
            "id_plan", "Nombre Socio", "DNI", "Descripcion", "Importe", "Fecha Inicio", "Fecha Fin"
        });

        try {
            String sql = "SELECT p.id_plan, " +
                         "CONCAT(s.nombre, ' ', s.apellido1, " +
                         "CASE WHEN s.apellido2 IS NOT NULL AND s.apellido2 != '' " +
                         "THEN CONCAT(' ', s.apellido2) ELSE '' END) AS NombreCompleto, " +
                         "s.dni, p.Descripcion, p.Importe, p.Fecha_Inicio, p.Fecha_Fin " +
                         "FROM plan p JOIN socio s ON p.Socio_ID = s.id_socio";

            PreparedStatement ps = conexion.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_plan"),
                    rs.getString("NombreCompleto"),
                    rs.getString("dni"),
                    rs.getString("Descripcion"),
                    rs.getDouble("Importe"),
                    rs.getDate("Fecha_Inicio"),
                    rs.getDate("Fecha_Fin")
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar tabla: " + e.getMessage());
        }

        jTablePlanes.getColumnModel().getColumn(0).setMinWidth(0);
        jTablePlanes.getColumnModel().getColumn(0).setMaxWidth(0);
        jTablePlanes.getColumnModel().getColumn(0).setWidth(0);
        jTablePlanes.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    }
    
    private int buscarIdPlan(String dni, String descripcion) {
        try {
            String sql = "SELECT p.id_plan FROM plan p " +
                         "JOIN socio s ON p.Socio_ID = s.id_socio " +
                         "WHERE s.dni = ? AND p.Descripcion = ?";
            PreparedStatement ps = conexion.prepareStatement(sql);
            ps.setString(1, dni);
            ps.setString(2, descripcion);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) return rs.getInt("id_plan");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al buscar ID del plan: " + e.getMessage());
        }
        return -1;
    }
    
    private Date convertirFecha(String fechaTexto){
        try{
            return new SimpleDateFormat("yyyy-MM-dd").parse(fechaTexto);
        }catch(ParseException e){
            JOptionPane.showMessageDialog(null, "Formato fecha inválido. Usa yyyy-MM-dd");
            return null;
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new JFrameGestionPlanes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePlanes;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
