/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.vista;

import java.sql.*;
import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Date;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import proyecto.modelo.Plan;
import proyecto.logica.PlanDAO;

/**
 *
 * @author DAM2Alu9
 */
public class JFrameGestionPlanes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameGestionPlanes.class.getName());
    
    
    PlanDAO dao = new PlanDAO();
    private javax.swing.table.TableRowSorter<DefaultTableModel> sorter;

    /**
     * Creates new form JFrameGestionPagos
     */
    private String rol;
    public JFrameGestionPlanes(String rol) {
        this.rol = rol;
        initComponents();
        cargarTabla();
        
        DefaultTableModel model = (DefaultTableModel) jTablePlanes.getModel();
        sorter = new javax.swing.table.TableRowSorter<>(model);
        jTablePlanes.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePlanes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPlan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldSocio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldFecha_Inicio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldFecha_Fin = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonAgregar = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jLabelBuscar = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTablePlanes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id_Plan", "Socio_ID", "Descripcion", "Fecha_Inicio", "Fecha_Fin"
            }
        ));
        jScrollPane1.setViewportView(jTablePlanes);

        jLabel1.setText("ID Plan");

        jTextFieldPlan.setMinimumSize(new java.awt.Dimension(90, 40));
        jTextFieldPlan.setName(""); // NOI18N

        jLabel2.setText("Descripcion");

        jTextFieldDescripcion.setMinimumSize(new java.awt.Dimension(90, 40));

        jLabel3.setText("Socio ID");

        jTextFieldSocio.setMinimumSize(new java.awt.Dimension(90, 40));

        jLabel4.setText("Fecha Inicio");

        jTextFieldFecha_Inicio.setMinimumSize(new java.awt.Dimension(90, 40));

        jLabel5.setText("Fecha Fin");

        jTextFieldFecha_Fin.setMinimumSize(new java.awt.Dimension(90, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jTextFieldPlan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldFecha_Fin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldFecha_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFecha_Fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldFecha_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAgregar);

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonBuscar);

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEliminar);

        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonActualizar);

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonVolver);

        jLabelBuscar.setText("Buscar");
        jLabelBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabelBuscarKeyReleased(evt);
            }
        });
        jPanel2.add(jLabelBuscar);

        jTextFieldBuscar.setPreferredSize(new java.awt.Dimension(84, 22));
        jTextFieldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarKeyReleased(evt);
            }
        });
        jPanel2.add(jTextFieldBuscar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        try {
            String textoSocio = jTextFieldSocio.getText().trim();
            int socioId = 0; // Valor por defecto para "sin socio"

            if (!textoSocio.isEmpty()) {
                socioId = Integer.parseInt(textoSocio);
            }

            String descripcion = jTextFieldDescripcion.getText();

            Date fechaInicio = convertirFecha(jTextFieldFecha_Inicio.getText());
            Date fechaFin = convertirFecha(jTextFieldFecha_Fin.getText());
            if(fechaInicio == null || fechaFin == null) return;

            Plan plan = new Plan(0, socioId, descripcion, fechaInicio, fechaFin);

            if(dao.insertar(plan)){
                JOptionPane.showMessageDialog(null, "Plan agregado correctamente");
                cargarTabla();
            }else{
                JOptionPane.showMessageDialog(null, "Error al agregar el plan");
            }

        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El ID de socio debe ser un número válido");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        // TODO add your handling code here:
        int idPlan = Integer.parseInt(jTextFieldPlan.getText());
        int socioId = Integer.parseInt(jTextFieldSocio.getText());
        String descripcion = jTextFieldDescripcion.getText();
        
        Date fechaInicio = convertirFecha(jTextFieldFecha_Inicio.getText());
        Date fechaFin = convertirFecha(jTextFieldFecha_Fin.getText());
        if(fechaInicio == null || fechaFin == null) return;
        
        Plan plan = new Plan(idPlan, socioId, descripcion, fechaInicio, fechaFin);
        
        if(dao.actualizar(plan)){
            JOptionPane.showMessageDialog(null, "Plan actualizado correctamente");
            cargarTabla();
        }else{
            JOptionPane.showMessageDialog(null, "No se ha podido actualizar el plan");
        }
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        String texto = jTextFieldPlan.getText().trim();

        // Validación simple
        if (texto.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecciona un plan primero");
            return;
        }

        try {
            int idPlan = Integer.parseInt(texto);

            // Eliminar directamente
            if(dao.eliminar(idPlan)){
                JOptionPane.showMessageDialog(null, "Plan eliminado");
                cargarTabla();
                jTextFieldPlan.setText(""); // Limpiar campo
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo eliminar. Puede que tenga usuarios asociados.");
            }

        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ID inválido");
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog("Introduce el Id del plan: ");
        
        if(input != null) try{
            int idPlan = Integer.parseInt(input);
            
            Plan p = dao.buscar(idPlan);
            
            if(p != null){
                jTextFieldPlan.setText(String.valueOf(p.getIdPlan()));
                jTextFieldSocio.setText(String.valueOf(p.getSocioId()));
                jTextFieldDescripcion.setText(p.getDescripcion());
                jTextFieldFecha_Inicio.setText(p.getFechaInicio().toString());
                jTextFieldFecha_Fin.setText(p.getFechaFin().toString());
                
            }else{
                JOptionPane.showMessageDialog(null, "No existe un plan con ese ID");
            }
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "ID inválido");
            
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
       JFrameMenuPrincipal menu = new JFrameMenuPrincipal(rol);
       menu.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jLabelBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabelBuscarKeyReleased
            // TODO add your handling code here:
    }//GEN-LAST:event_jLabelBuscarKeyReleased

    private void jTextFieldBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarKeyReleased
        // TODO add your handling code here:
                                                 
    String texto = jTextFieldBuscar.getText();

    if (texto.trim().length() == 0) {
        sorter.setRowFilter(null); // Mostrar todo
    } else {
        try {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto));
        } catch (PatternSyntaxException e) {
            System.out.println("Patrón inválido");
        }
    }


    }//GEN-LAST:event_jTextFieldBuscarKeyReleased

    
    private void cargarTabla(){
        DefaultTableModel model = (DefaultTableModel) jTablePlanes.getModel();
        model.setRowCount(0);
        
        List<Plan> lista = dao.listar();
        
        for (Plan p : lista) {
            model.addRow(new Object[]{
                p.getIdPlan(),
                p.getSocioId(),
                p.getDescripcion(),
                p.getFechaInicio(),
                p.getFechaFin()
            });
        }
    }
    
    private Date convertirFecha(String fechaTexto){
        try{
            return new SimpleDateFormat("yyyy-MM-dd").parse(fechaTexto);
        }catch(ParseException e){
            JOptionPane.showMessageDialog(null, "Formato fecha inválido. Usa yyyy-MM-dd");
            return null;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new JFrameGestionPlanes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePlanes;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldFecha_Fin;
    private javax.swing.JTextField jTextFieldFecha_Inicio;
    private javax.swing.JTextField jTextFieldPlan;
    private javax.swing.JTextField jTextFieldSocio;
    // End of variables declaration//GEN-END:variables
}
