/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.vista;

import ConexionBBDD.ConexionBBDD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.*;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import proyecto.logica.LogicaSocios;
import proyecto.modelo.Socio;

/**
 *
 * @author DAM2Alu14
 */
public class JFrameGestionSocios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameGestionSocios.class.getName());

    DefaultTableModel dtm;
    ConexionBBDD nueva;
    Connection conexion;
    TableRowSorter<TableModel> order;
    private String rol;
    
    // Carga en la tabla los datos desde LogicaSocios
    public void cargaDesdeLogica() {
        dtm.setRowCount(0); // Borra filas existentes

        for (Socio socio : LogicaSocios.getSocios()) {
            Object[] fila = new Object[8];
            fila[0] = socio.getNombre();
            fila[1] = socio.getApellido1();
            fila[2] = socio.getApellido2();
            fila[3] = socio.getDni();
            fila[4] = socio.getTelefono();
            fila[5] = socio.getCorreo();
            fila[6] = socio.getFecha_alta();
            fila[7] = socio.getEstado();

            dtm.addRow(fila);
        }

        // ACTUALIZACIÓN: Forzar actualización visual
    }
    /**
     * Creates new form JFrameGestionSocios
     */
    
    public void actualizarTabla() {
        // Recargar datos desde la base de datos
        LogicaSocios.cargaPrueba();
        // Actualizar la tabla visual
        cargaDesdeLogica();
    }
        
    public JFrameGestionSocios(String rol) {
        this.rol = rol;
        initComponents();

        // Inicializar conexión y modelo
        nueva = new ConexionBBDD();
        conexion = nueva.getConnection();
        dtm = new DefaultTableModel();
        jTableSocios.setModel(dtm);

        // Definir columnas
        String[] columnas = {"Nombre", "Apellido1", "Apellido2", "DNI", "Telefono", "Correo", "Fecha_Alta", "Estado"};
        dtm.setColumnIdentifiers(columnas);

        // Cargar datos desde la BBDD a LogicaSocios
        LogicaSocios.cargaPrueba();
        // Cargar datos en la tabla desde LogicaSocios
        cargaDesdeLogica();
        
        order = new TableRowSorter<>(dtm);
        jTableSocios.setRowSorter(order);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSocios = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButtonCargaClientes = new javax.swing.JButton();
        jButtonAlta = new javax.swing.JButton();
        jButtonBaja = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableSocios);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButtonCargaClientes.setText("Carga Socios");
        jButtonCargaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargaClientesActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCargaClientes);

        jButtonAlta.setText("Alta");
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAlta);

        jButtonBaja.setText("Baja");
        jButtonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonBaja);

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonEditar);

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonVolver);

        jLabel1.setText("Buscar");
        jPanel3.add(jLabel1);

        jTextFieldBuscar.setPreferredSize(new java.awt.Dimension(80, 22));
        jTextFieldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarActionPerformed(evt);
            }
        });
        jTextFieldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarKeyReleased(evt);
            }
        });
        jPanel3.add(jTextFieldBuscar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        int fila = jTableSocios.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un socio de la tabla");
            return;
        }

        // Obtener el DNI de la fila seleccionada
        String dni = jTableSocios.getValueAt(fila, 3).toString();
        
        // Buscar el socio por DNI en LogicaSocios
        Socio socioSeleccionado = null;
        for (Socio s : LogicaSocios.getSocios()) {
            if (s.getDni().equals(dni)) {
                socioSeleccionado = s;
                break;
            }
        }
        
        if (socioSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Error al obtener los datos del socio");
            return;
        }

        // Pasar el socio al JDialog
        JDialogEditarSocio jdec = new JDialogEditarSocio(this, true, conexion, socioSeleccionado);
        jdec.setVisible(true);
        
        // Refrescar la tabla después de editar
        cargaDesdeLogica();
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaActionPerformed
        // Comprobar que hay filas seleccionadas
        if (jTableSocios.getSelectedRowCount() > 0) {
            int[] seleccionados = jTableSocios.getSelectedRows();

            try {
                PreparedStatement ps = conexion.prepareStatement(
                    "UPDATE socio SET estado = ? WHERE DNI = ?"
                );

                // Recorrer los socios seleccionados
                for (int i = seleccionados.length - 1; i >= 0; i--) {

                    // Obtener DNI desde la tabla
                    String dni = jTableSocios.getValueAt(seleccionados[i], 3).toString();

                    // Buscar el socio en la lista lógica
                    Socio socio = null;
                    for (Socio s : LogicaSocios.getSocios()) {
                        if (s.getDni().equals(dni)) {
                            socio = s;
                            break;
                        }
                    }

                    // Si no se encuentra, pasar al siguiente
                    if (socio == null) continue;

                    // Marcar el socio como baja en la BBDD
                    ps.setString(1, "Baja");
                    ps.setString(2, dni);
                    ps.executeUpdate();

                    socio.setEstado("Baja");
                    LogicaSocios.editSocio(socio);
                }

                ps.close();

                // Avisar al usuario
                JOptionPane.showMessageDialog(this, "Socio/s dado/s de baja correctamente.");

                // Recargar datos desde la base de datos
                LogicaSocios.cargaPrueba();

                // Actualizar la tabla en pantalla
                cargaDesdeLogica();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(
                    this,
                    "Error al dar de baja socio.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
                );
            }

        } else {
            // Aviso si no se seleccionó ningún socio
            JOptionPane.showMessageDialog(
                this,
                "Seleccione al menos un socio para dar de baja.",
                "Aviso",
                JOptionPane.WARNING_MESSAGE
            );
        }
    }//GEN-LAST:event_jButtonBajaActionPerformed

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
        JDialogAltaSocio jdac = new JDialogAltaSocio(this, true, this.conexion);
        jdac.setVisible(true);

        LogicaSocios.cargaPrueba(); // Recargar desde BBDD
        cargaDesdeLogica(); // Actualizar tabla visual
    }//GEN-LAST:event_jButtonAltaActionPerformed

    private void jButtonCargaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargaClientesActionPerformed
        LogicaSocios.cargaPrueba();
        cargaDesdeLogica();
    }//GEN-LAST:event_jButtonCargaClientesActionPerformed

    private void jTextFieldBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarKeyReleased
        try {
            RowFilter<Object, Object> rf = RowFilter.regexFilter(jTextFieldBuscar.getText());
            order.setRowFilter(rf);
        } catch (PatternSyntaxException pse) {
            System.out.println("Bad regex pattern");
        }
    }//GEN-LAST:event_jTextFieldBuscarKeyReleased

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        JFrameMenuPrincipal jfap = new JFrameMenuPrincipal(rol);
        jfap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jTextFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarActionPerformed

    public void addSocio(Socio s) {
        LogicaSocios.addSocio(s);
        cargaDesdeLogica();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new JFrameGestionSocios("Administrador").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonBaja;
    private javax.swing.JButton jButtonCargaClientes;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSocios;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
