/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.vista;


import ConexionBBDD.ConexionBBDD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.*;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.export.ooxml.JRXlsxExporter;
import net.sf.jasperreports.export.SimpleExporterInput;
import net.sf.jasperreports.export.SimpleOutputStreamExporterOutput;
import net.sf.jasperreports.view.JasperViewer;
import proyecto.logica.LogicaPagos;
import proyecto.logica.LogicaSocios;
import proyecto.modelo.Pago;
import proyecto.modelo.Socio;

/**
 *
 * @author DAM2Alu14
 */
public class JFrameGestionPagos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameGestionPagos.class.getName());

    // Variables
    DefaultTableModel dtm;
    DefaultTableModel modelo;
    ConexionBBDD nueva;
    Connection conexion;
    TableRowSorter<TableModel> orderPagos;
    TableRowSorter<TableModel> orderPendientes;

    private String rol;
    
    /**
     * Creates new form JFramePagos
     */
    public JFrameGestionPagos(String rol) {
        this.rol = rol;
        initComponents();
        
        nueva = new ConexionBBDD();
        conexion = nueva.getConnection();
        dtm = new DefaultTableModel();
        modelo = new DefaultTableModel();
        
        LogicaSocios.cargaPrueba(); // Carga los socios a una lista
        LogicaPagos.cargaPrueba(); // Carga los pagos a una lista
        cargaID();
        
        
        listarPagos();
        // Ordeno los JTable segun Buscar
        orderPagos = new TableRowSorter<>(jTablePagos.getModel());
        jTablePagos.setRowSorter(orderPagos);

        cargarPagosPendientes();
        // Ordeno los JTable segun Buscar
        orderPendientes = new TableRowSorter<>(jTablePagosPendientes.getModel());
        jTablePagosPendientes.setRowSorter(orderPendientes);           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTabbedPanelAplicacion = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxId = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldApellido2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerFechaPago = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldImporte = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButtonRegistrarPago = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePagosPendientes = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldBuscar1 = new javax.swing.JTextField();
        jButtonPagosPendientes = new javax.swing.JButton();
        jButtonImprimirPagosPendientes = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePagos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonPagos = new javax.swing.JButton();
        jButtonImprimirPagosPorCliente1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonTabPrev = new javax.swing.JButton();
        jButtonTabNext = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GESTIÓN DE PAGOS");

        jPanel1.setLayout(new java.awt.GridLayout(9, 2, 10, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("REGISTRAR PAGO");
        jPanel1.add(jLabel1);
        jPanel1.add(jLabel8);

        jLabel3.setText("Socio_ID");
        jPanel1.add(jLabel3);

        jComboBoxId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxIdItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBoxId);

        jLabel10.setText("Nombre Socio");
        jPanel1.add(jLabel10);
        jPanel1.add(jTextFieldNombre);

        jLabel11.setText("1º Apellido Socio");
        jPanel1.add(jLabel11);
        jPanel1.add(jTextFieldApellido1);

        jLabel12.setText("2º Apellido Socio");
        jPanel1.add(jLabel12);
        jPanel1.add(jTextFieldApellido2);

        jLabel4.setText("Fecha Pago");
        jPanel1.add(jLabel4);

        jSpinnerFechaPago.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerFechaPago.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFechaPago, "dd/MM/yy hh:mm"));
        jPanel1.add(jSpinnerFechaPago);

        jLabel5.setText("Importe");
        jPanel1.add(jLabel5);
        jPanel1.add(jTextFieldImporte);

        jLabel7.setText("Estado");
        jPanel1.add(jLabel7);

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Pagado", "Vencido" }));
        jPanel1.add(jComboBoxEstado);
        jPanel1.add(jLabel9);

        jButtonRegistrarPago.setText("Registrar Pago");
        jButtonRegistrarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarPagoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegistrarPago);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(335, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
        );

        jTabbedPanelAplicacion.addTab("Registrar Pago", jPanel4);

        jTablePagosPendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePagosPendientes);

        jLabel13.setText("Buscar");

        jTextFieldBuscar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBuscar1KeyReleased(evt);
            }
        });

        jButtonPagosPendientes.setText("Recargar Pagos Pendientes");
        jButtonPagosPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagosPendientesActionPerformed(evt);
            }
        });

        jButtonImprimirPagosPendientes.setText("Imprimir Pagos Pendientes");
        jButtonImprimirPagosPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirPagosPendientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPagosPendientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonImprimirPagosPendientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonPagosPendientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonImprimirPagosPendientes))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPanelAplicacion.addTab("Ver Pagos Pendientes", jPanel5);

        jTablePagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablePagos);

        jLabel6.setText("Buscar");

        jTextFieldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarKeyReleased(evt);
            }
        });

        jButtonPagos.setText("Recargar Pagos");
        jButtonPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagosActionPerformed(evt);
            }
        });

        jButtonImprimirPagosPorCliente1.setText("Imprimir Pagos Por DNI y Estado");
        jButtonImprimirPagosPorCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirPagosPorCliente1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonImprimirPagosPorCliente1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPagos)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonImprimirPagosPorCliente1)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPanelAplicacion.addTab("Listar Pago", jPanel3);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonTabPrev.setText("<");
        jButtonTabPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTabPrevActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonTabPrev);

        jButtonTabNext.setText(">");
        jButtonTabNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTabNextActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonTabNext);

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonVolver);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanelAplicacion)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPanelAplicacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Carga los id disponibles al jComboBoxId
    public void cargaID(){
        jComboBoxId.removeAllItems();
        for (Socio socio : LogicaSocios.getSocios()) {
            jComboBoxId.addItem(String.valueOf(socio.getId_socio()));
        }
    }
    
    private void jButtonTabPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTabPrevActionPerformed
        // TODO add your handling code here:
        if (jTabbedPanelAplicacion.getSelectedIndex() == 0) {
            jTabbedPanelAplicacion.setSelectedIndex(jTabbedPanelAplicacion.getTabCount()-1);
        } else
        jTabbedPanelAplicacion.setSelectedIndex(jTabbedPanelAplicacion.getSelectedIndex()-1);
    }//GEN-LAST:event_jButtonTabPrevActionPerformed

    private void jButtonTabNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTabNextActionPerformed
        // TODO add your handling code here:
        if (jTabbedPanelAplicacion.getSelectedIndex() ==jTabbedPanelAplicacion.getTabCount()-1) {
            jTabbedPanelAplicacion.setSelectedIndex(0);
        } else
        jTabbedPanelAplicacion.setSelectedIndex(jTabbedPanelAplicacion.getSelectedIndex()+1);
    }//GEN-LAST:event_jButtonTabNextActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // Cierra la ventana actual y abre el menu principal
        JFrameMenuPrincipal jfmp = new JFrameMenuPrincipal(rol);
        jfmp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jTextFieldBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarKeyReleased
        // Ordena la tabla segun lo escrito en el FieldBuscar
        try {
            RowFilter<Object, Object> rf = RowFilter.regexFilter(jTextFieldBuscar.getText());
            orderPagos.setRowFilter(rf);
        } catch (PatternSyntaxException pse) {
            System.out.println("Patrón inválido");
        }
    }//GEN-LAST:event_jTextFieldBuscarKeyReleased

    // Acutalizo los campos nombre y apellidos segun el id seleccionado
    private void jComboBoxIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxIdItemStateChanged
        if(jComboBoxId.getSelectedItem() != null) {
            int id = Integer.parseInt(jComboBoxId.getSelectedItem().toString());
            Socio s = LogicaSocios.getSocio(id);
            jTextFieldNombre.setText(s.getNombre());
            jTextFieldApellido1.setText(s.getApellido1());
            jTextFieldApellido2.setText(s.getApellido2());

            // Buscar el importe del plan del socio
            try {
                PreparedStatement ps = conexion.prepareStatement(
                    "SELECT Importe FROM plan WHERE Socio_ID = ?"
                );
                ps.setInt(1, id);
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    jTextFieldImporte.setText(String.valueOf(rs.getDouble("Importe")));
                    jTextFieldImporte.setEditable(false); // No editable, viene del plan
                } else {
                    jTextFieldImporte.setText("");
                    jTextFieldImporte.setEditable(true); // Sin plan, se introduce manualmente
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error al buscar plan: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jComboBoxIdItemStateChanged

    private void jTextFieldBuscar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscar1KeyReleased
        try {
            RowFilter<Object, Object> rf = RowFilter.regexFilter(jTextFieldBuscar1.getText());
            orderPendientes.setRowFilter(rf);
        } catch (PatternSyntaxException pse) {
            System.out.println("Patrón inválido");
        }
    }//GEN-LAST:event_jTextFieldBuscar1KeyReleased

    private void jButtonRegistrarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarPagoActionPerformed
                                                     
        if (jComboBoxId.getSelectedItem() == null || jTextFieldImporte.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Debe seleccionar un socio con un plan asignado.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            int socioId = Integer.parseInt(jComboBoxId.getSelectedItem().toString());

            // Verificar que el socio tiene plan
            PreparedStatement checkPlan = conexion.prepareStatement(
                "SELECT COUNT(*) FROM plan WHERE Socio_ID = ?"
            );
            checkPlan.setInt(1, socioId);
            ResultSet rsPlan = checkPlan.executeQuery();
            rsPlan.next();
            if (rsPlan.getInt(1) == 0) {
                JOptionPane.showMessageDialog(this,
                    "El socio no tiene un plan asignado. No se puede registrar el pago.",
                    "Error", JOptionPane.ERROR_MESSAGE);
                rsPlan.close();
                checkPlan.close();
                return;
            }
            rsPlan.close();
            checkPlan.close();

            java.util.Date fechaUtil = (java.util.Date) jSpinnerFechaPago.getValue();
            double importe = Double.parseDouble(jTextFieldImporte.getText());
            String estado = jComboBoxEstado.getSelectedItem().toString();

            // Buscar si el socio tiene un pago pendiente
            PreparedStatement checkPendiente = conexion.prepareStatement(
                "SELECT id_pago FROM pago WHERE socio_id = ? AND estado = 'Pendiente' LIMIT 1"
            );
            checkPendiente.setInt(1, socioId);
            ResultSet rsPendiente = checkPendiente.executeQuery();

            if (rsPendiente.next() && !estado.equals("Pendiente")) {
                // Existe pendiente Y estamos pagando → actualizar el pendiente existente
                int idPendiente = rsPendiente.getInt("id_pago");
                rsPendiente.close();
                checkPendiente.close();

                PreparedStatement psUpdate = conexion.prepareStatement(
                    "UPDATE pago SET fecha_pago = ?, importe = ?, estado = ? WHERE id_pago = ?"
                );
                psUpdate.setDate(1, new java.sql.Date(fechaUtil.getTime()));
                psUpdate.setDouble(2, importe);
                psUpdate.setString(3, estado);
                psUpdate.setInt(4, idPendiente);
                psUpdate.executeUpdate();
                psUpdate.close();

                // Actualizar también en memoria
                for (Pago pago : LogicaPagos.getPagos()) {
                    if (pago.getId_pago() == idPendiente) {
                        pago.setFecha_pago(fechaUtil);
                        pago.setImporte(importe);
                        pago.setEstado(estado);
                        break;
                    }
                }

                JOptionPane.showMessageDialog(this,
                    "Pago pendiente actualizado correctamente.",
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);

            } else {
                // No hay pendiente O se está creando un nuevo pago pendiente → insertar
                rsPendiente.close();
                checkPendiente.close();

                String sqlInsert = "INSERT INTO pago (socio_id, fecha_pago, importe, estado) VALUES (?, ?, ?, ?)";
                PreparedStatement ps = conexion.prepareStatement(sqlInsert);
                ps.setInt(1, socioId);
                ps.setDate(2, new java.sql.Date(fechaUtil.getTime()));
                ps.setDouble(3, importe);
                ps.setString(4, estado);
                ps.executeUpdate();
                ps.close();

                // Obtener el id generado y añadir a memoria
                int ultimoId = -1;
                Statement st = conexion.createStatement();
                ResultSet rs = st.executeQuery("SELECT MAX(id_pago) FROM pago");
                if (rs.next()) ultimoId = rs.getInt(1);
                rs.close();
                st.close();

                Pago nuevoPago = new Pago(socioId, fechaUtil, importe, estado);
                nuevoPago.setId_pago(ultimoId);
                LogicaPagos.addPago(nuevoPago);

                JOptionPane.showMessageDialog(this,
                    "Pago registrado correctamente.",
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }

            // Limpiar campos y recargar tablas
            jTextFieldImporte.setText("");
            jSpinnerFechaPago.setValue(new java.util.Date());
            jComboBoxEstado.setSelectedIndex(0);
            actualizarTablas();

        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this,
                "El importe debe ser un número válido.",
                "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                "Error al registrar el pago: " + ex.getMessage(),
                "Error SQL", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonRegistrarPagoActionPerformed

    private void jButtonPagosPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagosPendientesActionPerformed
        LogicaPagos.cargaPrueba();
        cargarPagosPendientes();
    }//GEN-LAST:event_jButtonPagosPendientesActionPerformed

    private void jButtonPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagosActionPerformed
        LogicaPagos.cargaPrueba();
        listarPagos();
    }//GEN-LAST:event_jButtonPagosActionPerformed

    private void jButtonImprimirPagosPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirPagosPendientesActionPerformed
            String fileJasper = "informes/pagosPendientes.jrxml";
            try{
                JasperReport report = JasperCompileManager.compileReport(fileJasper);
                //Map parameters = new HashMap();
                //parameters.put("PAIS", jComboBoxPaises.getSelectedItem().toString());
                JasperPrint print
                        = JasperFillManager.fillReport(report, null, nueva.getConnection());
                JasperExportManager.exportReportToPdfFile(print, "informes\\pagosPendientes.pdf");
                JRXlsxExporter exporter = new JRXlsxExporter();
                exporter.setExporterInput(new SimpleExporterInput(print));
                exporter.setExporterOutput(new SimpleOutputStreamExporterOutput("informes\\pagosPendientes.xlsx"));
                exporter.exportReport();
                JasperViewer.viewReport(print, false);

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null,"Se produjo un error al leer el archivo .jrxml");
            }
    }//GEN-LAST:event_jButtonImprimirPagosPendientesActionPerformed

    private void jButtonImprimirPagosPorCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirPagosPorCliente1ActionPerformed
        String fileJasper = "informes/pagosPorEstadoDNI.jrxml";

        try {
            // Pedir DNI
            String dni = JOptionPane.showInputDialog(null, "Ingrese el DNI del socio:");

            if (dni == null || dni.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "DNI no válido.");
                return;
            }

            // IMPORTANTE: limpiar espacios ocultos
            dni = dni.trim();

            // Estados reales de tu tabla pago
            String[] estados = {"Pagado", "Pendiente"};
            String estado = (String) JOptionPane.showInputDialog(
                    null,
                    "Seleccione el estado del pago:",
                    "Estado",
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    estados,
                    estados[0]);

            if (estado == null || estado.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Estado no seleccionado.");
                return;
            }

            estado = estado.trim();

            // Parámetros EXACTOS que usa el JRXML
            Map<String, Object> parametros = new HashMap<>();
            parametros.put("DNI", dni);        // debe llamarse DNI
            parametros.put("Estado", estado);  // debe llamarse Estado

            // Compilar informe
            JasperReport report = JasperCompileManager.compileReport(fileJasper);

            // Rellenar informe con conexión
            JasperPrint print = JasperFillManager.fillReport(
                    report,
                    parametros,
                    nueva.getConnection()
            );

            // Comprobación clave (esto te dirá si hay datos o no)
            if (print.getPages().isEmpty()) {
                JOptionPane.showMessageDialog(null, 
                    "No hay pagos para ese DNI y estado.");
                return;
            }

            // Exportar PDF
            String nombreArchivo = "informes/pagos_" + dni + "_" + estado + ".pdf";
            JasperExportManager.exportReportToPdfFile(print, nombreArchivo);

            // Mostrar visor
            JasperViewer.viewReport(print, false);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, 
                "Error al generar el informe: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonImprimirPagosPorCliente1ActionPerformed

    public void actualizarTablas() {
        listarPagos();
        cargarPagosPendientes();
    }
          
    private void listarPagos() {
        dtm = new DefaultTableModel();
        dtm.addColumn("ID");
        dtm.addColumn("Socio");
        dtm.addColumn("DNI");
        dtm.addColumn("Fecha Pago");
        dtm.addColumn("Importe");
        dtm.addColumn("Estado");

        // Muestra los datos desde LogicaPagos
        for (Pago pago : LogicaPagos.getPagos()) {
            Socio socio = LogicaSocios.getSocio(pago.getSocio_id());
            if (socio != null) {
                String nombreCompleto = socio.getNombre() + " " + socio.getApellido1() + 
                    (socio.getApellido2() != null && !socio.getApellido2().isEmpty() ? " " + socio.getApellido2() : "");
                
                // Formatear fecha como java.sql.Date
                java.sql.Date fechaSQL = new java.sql.Date(pago.getFecha_pago().getTime());
                
                dtm.addRow(new Object[]{
                    pago.getId_pago(),
                    nombreCompleto,
                    socio.getDni(),
                    fechaSQL,
                    pago.getImporte(),
                    pago.getEstado()
                });
            }
        }

        jTablePagos.setModel(dtm);
        orderPagos = new TableRowSorter<>(jTablePagos.getModel());
        jTablePagos.setRowSorter(orderPagos);
    }
    
    
    private void cargarPagosPendientes() {
        modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Socio");
        modelo.addColumn("DNI");
        modelo.addColumn("Fecha Pago");
        modelo.addColumn("Importe");
        modelo.addColumn("Estado");

        // Muestra solo los pagos pendientes desde LogicaPagos
        for (Pago pago : LogicaPagos.getPagosPendientes()) {
            Socio socio = LogicaSocios.getSocio(pago.getSocio_id());
            if (socio != null) {
                String nombreCompleto = socio.getNombre() + " " + socio.getApellido1() + 
                    (socio.getApellido2() != null && !socio.getApellido2().isEmpty() ? " " + socio.getApellido2() : "");
                
                // Formatear fecha como java.sql.Date
                java.sql.Date fechaSQL = new java.sql.Date(pago.getFecha_pago().getTime());
                
                modelo.addRow(new Object[]{
                    pago.getId_pago(),
                    nombreCompleto,
                    socio.getDni(),
                    fechaSQL,
                    pago.getImporte(),
                    pago.getEstado()
                });
            }
        }

        jTablePagosPendientes.setModel(modelo);
        orderPendientes = new TableRowSorter<>(jTablePagosPendientes.getModel());
        jTablePagosPendientes.setRowSorter(orderPendientes);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new JFrameGestionPagos("Administrador").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonImprimirPagosPendientes;
    private javax.swing.JButton jButtonImprimirPagosPorCliente1;
    private javax.swing.JButton jButtonPagos;
    private javax.swing.JButton jButtonPagosPendientes;
    private javax.swing.JButton jButtonRegistrarPago;
    private javax.swing.JButton jButtonTabNext;
    private javax.swing.JButton jButtonTabPrev;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JComboBox<String> jComboBoxId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerFechaPago;
    private javax.swing.JTabbedPane jTabbedPanelAplicacion;
    private javax.swing.JTable jTablePagos;
    private javax.swing.JTable jTablePagosPendientes;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldApellido2;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextFieldBuscar1;
    private javax.swing.JTextField jTextFieldImporte;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
